### ISSUE TITLE
Setup Continuous Integration.  

### ISSUE THREAD

**Issue by mikeumus** [NewSpaceNYC/Starseed#26]
Just have to decide between [CircleCi](https://circleci.com/) and CodeShip. Probably going with [CodeShip](https://codeship.com/) just because I used it in the past.

**Comment by seanauriti** [comment]
CodeShip sounds good... This is low priority, let's get some users and companies signed up first.

**Comment by mikeumus** [comment]
It's super easy to setup and required so that we don't deploy and break production. No worries, I've got it.

**Comment by seanauriti** [comment]
Added codeship

**Comment by mikeumus** [comment]
Testing still needs to be setup within Codacy.

**Comment by seanauriti** [comment]
Sounds like a new issue, - CI is setup...

**Comment by mikeumus** [comment]
CI is supposed to run tests before deploying, that's the point of it.

**Comment by mikeumus** [comment]
@seanauriti is it possible to add us to the Codeship account or do they have Orgs there, I forget.

**Comment by seanauriti** [comment]
added
